### ISSUE TITLE
ログイン成功したのかわからないです

### ISSUE THREAD

**Issue by akinori5** [ikuo/garaponoid#1]
ログインしてもまたログインボタンが出るので、失敗？と思いきや、メニューにログアウト、と表示されるので、ああログインできていたのかとわかります。
ログイン後は、トップ画面に遷移してくれるといいかと思いました。

**Comment by ikuo** [comment]
ログイン後、ホントは最近の番組が表示されるはずなので、どこかでエラーになってるようですね。
ちなみに宅外接続環境です？

今エラー処理が弱いので、中で何が起きてるか分かるようにしようと思います。

**Comment by ikuo** [comment]
エラー発生時にAndroid標準のエラーレポートが発動していなかったようなので、直しました。
この修正を他の不具合修正とともに、バージョン 0.2.11 としてGoogle Playに公開しました。

お手数ですが、再度ログインを試していただければ幸いです。

**Comment by akinori5** [comment]
宅外視聴はまだ試せていません、すいません。
バージョンアップしてインストールしたらエラーが出て起動後進めませんでした。
https://www.dropbox.com/s/mivm8uwq8wlil1v/Screenshot_2014-06-23-02-06-27.png
エラーのスクショです。

**Comment by ikuo** [comment]
スクショありがとうございます！
反応遅くなってすみません。ちょっと調べてみます。

<del>再度機会がございましたら、`failed to connect to ...`のメッセージの右側に隠れている部分も頂けますと幸いです。</del>

**Comment by ikuo** [comment]
ガラポンTVのWebからの設定でポート番号が80番_以外_の場合、宅内接続だとスクショのようなエラーになることが分かりました。

この修正を先ほど version 0.2.12 としてGoogle Playに公開しましたので、お手数ですがお試し頂ければ幸です。
